[package]
name = "epsi_proj_appli_mobile_serveur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluer = { version = "0.17.0", features = ["full"] }
tokio = "1.36.0"
